backend:
  name: git-gateway
  branch: main 

media_folder: "src/uploads"
public_folder: "/uploads"

collections:
  - name: "cybersecurity"
    label: "IT & Cybersecurity"
    folder: "src/cybersecurity"
    create: true
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post.njk"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
      
  - name: "faith"
    label: "Faith"
    folder: "src/faith"
    create: true
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post.njk"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
      
  - name: "episodes"
    label: "Episodes & Interviews"
    folder: "src/episodes"
    create: true
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post.njk"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
      
  - name: "financial"
    label: "Financial Market"
    folder: "src/financial"
    create: true
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post.njk"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
